@startuml
title Ejercicio 10

state 1 : n = 5
state 2 #LightGreen: while n > 0
state 3 #LightGreen: n % 2 == 0
state 4 : print("Par")
state 5 : print("Impar")
state 6 : n -= 1
state 7 : print("Listo")
state 8 : Exit

1 --> 2
2 --> 3 : true
2 --> 7 : false
3 --> 4 : true
3 --> 5 : false
4 --> 6
5 --> 6
6 --> 2
7 --> 8

note as n1
    Complejidad ciclomática:

    * Nº decisiones del código: 2
    * V(G) = 2 + 1 = 3

    * 1) Método decisiones:
    ** V(G) = numero de decisiones + 1

    * 2) Método E - N + 2P:
    ** V(G) = E - N + 2P

    ** N (nodos) = 8
    ** E (aristas) = 9
    ** P (componentes) = 1

    ** V(G) = 9 - 8 + 2(1) = 3

    * Conjunto de caminos básicos: 3
    ** Camino 1: 1 -> 2 -> 7 -> 8
    ** Camino 2: 1 -> 2 -> 3 -> 4 -> 6 -> 2 -> 7 -> 8
    ** Camino 3: 1 -> 2 -> 3 -> 5 -> 6 -> 2 -> 7 -> 8

    * Grafo de flujo
    ** N1: inicializar n = 5
    ** N2: While n > 0
    ** N3: Evaluar n % 2 == 0
    ** N4: imprimir Par
    ** N5: imprimir Impar
    ** N6: decrementar n
    ** N7: imprimir Listo
    ** N8: Salida
end note
@enduml